# Generated by Django 4.1.5 on 2023-01-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='room',
            new_name='post_id',
        ),
    ]
